lr: 1e-4
lr_backbone: 1e-5
batch_size: 2
weight_decay: 1e-4
epochs: 300
lr_drop: 200
clip_max_norm: 0.1

# Model parameters
frozen_weights: null
backbone: resnet50
dilation: false
position_embedding: sine

# Transformer
enc_layers: 6
dec_layers: 6
dim_feedforward: 2048
hidden_dim: 256
dropout: 0.1
nheads: 8
num_queries: 100
pre_norm: false

# Segmentation
masks: false

# Loss
aux_loss: true
set_cost_class: 1.0
set_cost_bbox: 5.0
set_cost_giou: 2.0

# Loss coefficients
mask_loss_coef: 1.0
dice_loss_coef: 1.0
bbox_loss_coef: 5.0
giou_loss_coef: 2.0
eos_coef: 0.1

# Dataset parameters
dataset_file: coco
coco_path: null
coco_panoptic_path: null
remove_difficult: false

# Output and training parameters
output_dir: ''
device: cuda
seed: 42
resume: ''
start_epoch: 0
eval: false
num_workers: 2

# Distributed training
world_size: 1
dist_url: 'env://'
